### ISSUE TITLE
Could not load file or assembly System.Data.SqlClient, Version=4.5.0.0

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db#1710]
````
Unhandled Exception: System.TypeInitializationException: The type initializer for 'LinqToDB.Data.DataConnection' threw an exception. ---> System.TypeInitializationException: The type initializer for 'LinqToDB.DataProvider.SqlServer.SqlServerTools' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Data.SqlClient, Version=4.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at LinqToDB.DataProvider.SqlServer.SqlServerDataProvider..ctor(String name, SqlServerVersion version)
   at LinqToDB.DataProvider.SqlServer.SqlServerTools..cctor() in C:\projects\linq2db\Source\LinqToDB\DataProvider\SqlServer\SqlServerTools.cs:line 22
   --- End of inner exception stack trace ---
   at LinqToDB.DataProvider.SqlServer.SqlServerTools.GetDataProvider(SqlServerVersion version) in C:\projects\linq2db\Source\LinqToDB\DataProvider\SqlServer\SqlServerTools.cs:line 195
   at LinqToDB.Data.DataConnection..cctor() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 576
   --- End of inner exception stack trace ---
   at LinqToDB.Data.DataConnection.set_DefaultSettings(ILinqToDBSettings value) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 548
   at Hyw.Data.LinqToDBCollectionExtensions.AddLinqToDB(IServiceCollection services, Boolean isLogger) in D:\VsProjects\Hyw\src\Hyw.Data\LinqToDBCollectionExtensions.cs:line 17
   at Hyw.ConsoleTest.Program.BuildDi() in D:\VsProjects\Hyw\test\Hyw.ConsoleTest\Program.cs:line 82
   at Hyw.ConsoleTest.Program.Main(String[] args) in D:\VsProjects\Hyw\test\Hyw.ConsoleTest\Program.cs:line 29
````

````csharp
  public static class LinqToDBCollectionExtensions
    {
        // ReSharper disable once InconsistentNaming
        public static void AddLinqToDB(this IServiceCollection services, bool isLogger = false)
        {
            //注册配置 如果有多个db 请在 MySettings中配置
           // LINE 17
            DataConnection.DefaultSettings = new MySettings();
            if (isLogger)
            {
                DataConnection.TurnTraceSwitchOn();
                DataConnection.WriteTraceLine = (s1, s2) =>
                {
                    var logger = services.BuildServiceProvider().GetService<ILoggerFactory>().CreateLogger(s2);
                    logger.LogInformation(s1);
                    Console.WriteLine(s1);
                };
            }

            LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;

            services.AddScoped<IDbContextProvider, DbContextProvider>();
        }
    }
````

````csharp
public class MySettings : ILinqToDBSettings
    {
        public IEnumerable<IDataProviderSettings> DataProviders => Enumerable.Empty<IDataProviderSettings>();

        public string DefaultConfiguration => "SqlServer";
        public string DefaultDataProvider => "SqlServer";

        public IEnumerable<IConnectionStringSettings> ConnectionStrings
        {
            get
            {
                yield return
                    new ConnectionStringSettings
                    {
                        Name = "Hyw",
                        ProviderName = ProviderName.SqlServer2008,
                        ConnectionString = @""
                    };
              }
        }
    }
````
in a console application  

linq2db.SqlServer 2.7.0
Microsoft.NETCore.App 2.2.0

**Comment by quan01994** [comment]
in asp.net core , It won't throw this exception

**Comment by sdanyliv** [comment]
Try to install this package yourself.

**Comment by quan01994** [comment]
emm，
i want install System.Data.SqlClient 4.5.0 
it throw this exception
```
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	NU1605	检测到包降级: System.Data.SqlClient 从 4.5.1 降级到 4.5.0。直接从项目引用包以选择不同版本。 
 Hyw.ConsoleTest -> Hyw.Data -> linq2db.SqlServer 2.7.0 -> linq2db 2.7.0 -> System.Data.SqlClient (>= 4.5.1) 
 Hyw.ConsoleTest -> System.Data.SqlClient (>= 4.5.0)	Hyw.ConsoleTest	D:\VsProjects\Hyw\test\Hyw.ConsoleTest\Hyw.ConsoleTest.csproj	1	
```

**Comment by sdanyliv** [comment]
Currently yes but we plan to remove this direct dependency.
https://github.com/linq2db/linq2db/issues/1704#issuecomment-487624581

**Comment by quan01994** [comment]
Can only roll back the version now

**Comment by sdanyliv** [comment]
Why you have stick with 4.5 version? We recently updated reference because of important bug-fix in SqlClient library.

**Comment by quan01994** [comment]
I used linq2db 2.7.0, but he reported missing SqlClient 4.5.0 in the console application . I don't know what caused this.

**Comment by quan01994** [comment]
I installed the latest version of sqlClient by nuget . this problem was solved.

**Comment by quan01994** [comment]
I understand what you mean wrong, I thought you told me to install SqlClient 4.5.0. 
(￣▽￣)"

**Comment by weitzhandler** [comment]
In a nopcommerce app I'm still facing this issue:
![image](https://github.com/linq2db/linq2db/assets/2716316/0417ba3f-cb72-4ee1-92eb-e4e0d9961a78)

I've trying installing the package manually and the issue still persists.

**Comment by weitzhandler** [comment]
For some mysterious reason after disabling Just My Code issue is gone.
