### ISSUE TITLE
MapValue and greater/smaller comparison

### ISSUE THREAD

**Issue by boris-turk** [linq2db/linq2db#2041]
Hi,

I discovered an issue with enum mappings. Consider the following unit test:
```cs
[Test]
public void MappedEnumGreaterAndLessComparison([IncludeDataSources(ProviderName.Access)] string context)
{
	using (var db = GetDataContext(context))
	{
		var result = db.GetTable<Person>()
			.Where(_ => _.Gender > Gender.Female)
			.Where(_ => _.Gender <= Gender.Male)
			.ToList();

		Assert.IsTrue(result.All(_ => _.Gender == Gender.Male));
	}
}
```
I would expect the linq2db to produce the following query (similar to the != operator):
```sql
SELECT
	[_].[FirstName],
	[_].[PersonID],
	[_].[LastName],
	[_].[MiddleName],
	[_].[Gender]
FROM
	[Person] [_]
WHERE
	[_].[Gender] > 'F' AND [_].[Gender] <= 'M'
```
But it produces the following query, which of course breaks down with exception 'Data type mismatch in criteria expression.' (Access provider):
```sql
SELECT
	[_].[FirstName],
	[_].[PersonID],
	[_].[LastName],
	[_].[MiddleName],
	[_].[Gender]
FROM
	[Person] [_]
WHERE
	[_].[Gender] > 1 AND [_].[Gender] <= 0
```
Would it be possible to improve linq2db, so that the mapping is applied also for other comparison types (<, >, <=, >=)? Thank you in advance for any kind of help/feedback and best regards,

Boris

**Comment by boris-turk** [comment]
Thanks @sdanyliv for fixing the markup, I figured out just now how to do it correctly ... :)

**Comment by sdanyliv** [comment]
Looks like a bug, will check what we can do here.

**Comment by MaceWindu** [comment]
Looks like it is another case of C# compiler being smart cookie and replacing values in expressions. In this case it replaces enum constants with integer constants....

**Comment by MaceWindu** [comment]
Fixed #2109

**Comment by boris-turk** [comment]
Hi @MaceWindu,

thanks a lot for taking the time to solve the issue and sorry for my very late reply. I did test the bug fix in our application, but I am still getting an error, now a different one. Obviously the declaration of enum parameter is wrong, see the attached SQL query screenshot. Unfortunately I am not able to prepare a failing unit test because I cannot compile the latest linq2db source code (I am still on VS 2017). Is there something you can do about this error? Thank you in advance and best regards,

Boris

![image](https://user-images.githubusercontent.com/14542258/82016914-3fe35780-9682-11ea-8be6-e5c6084eff34.png)

**Comment by MaceWindu** [comment]
DECLARE section of logged sql is approximate and could display wrong type. In your case you should look at value, which is correct
