### ISSUE TITLE
Status v4

### ISSUE THREAD

**Issue by stefandevo** [linq2db/linq2db#3417]
Hi
Just wondering when v4 will be released? It's a couple of monhts now. Furthermore, looking at the documentation site it seems no work has been done for some time. Just trying to figure out which orm I should use. I like this project but not sure whether this is a safe choice over EF Core 6. Thanks for the guidance.

**Comment by jods4** [comment]
I have no idea when v4 will be released, but as a watcher of this repo I can tell you that "it seems no work has been done for some time." is really far from the truth.

A lot of work was done on Query Hints #3297, which was recently merged into the upcoming v4 preview 11.

Last month a ton of work was also put into refactoring the parsing engine #3401, which is something the team wants to do for v4 as well.

**Comment by Usaga** [comment]
This is a mature ORM and under active development. Bugs are fixed very quickly. We are porting our huge project from EF6 to linq2db and I can tell this goes very well.

It is totally fine to chose linq2db over EF. It has so much more features and flexibility that I don't really understand what should made someone to use EF after meeting with linq2db.

**Comment by stefandevo** [comment]
> I have no idea when v4 will be released, but as a watcher of this repo I can tell you that "it seems no work has been done for some time." is really far from the truth.
> 
> 

I am sorry, did not want to offend the contributors. Was pointing towards the V4 finalization. 

Good to hear that this lib is still getting the necessary attention, features and fixes!

**Comment by stefandevo** [comment]
> This is a mature ORM and under active development. Bugs are fixed very quickly. We are porting our huge project from EF6 to linq2db and I can tell this goes very well.
> 

Great to hear this!
Did you move from EF6 or from EF Core 6 ?  I understood theat ef core 6 is much better. 

> 
> 
> It is totally fine to chose linq2db over EF. It has so much more features and flexibility that I don't really understand what should made someone to use EF after meeting with linq2db.

Cool!

**Comment by Usaga** [comment]
We move from "classic" EF6. EF Core 6 definitely better then EF6, but still lucks behind linq2db. We were needed of things that still not in EF Core and it's unluckily will be implemented at all. So, the decision was obvious. And after about a year of using this ORM I see we chosen right.

**Comment by MaceWindu** [comment]
We currently working on big features for v4, so there is no much activity on other stuff.

**Comment by jogibear9988** [comment]
There are also many issues marked as good first issue, if someone likes to help: https://github.com/linq2db/linq2db/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22

okay, I have to apologize, I for myself didn't help much in the last years

**Comment by MaceWindu** [comment]
v4 release is scheduled to 21 of April
