### ISSUE TITLE
SQLite FTS table Match support

### ISSUE THREAD

**Issue by peterzt** [linq2db/linq2db#773]
Greetings,

Can you please tell how to code support for Match operator (Full text search in SQLite)

Example query:

select f1,f2 from t3 where t3 match 'someText*'

The above performs match against all fields. 

Thanks in advance,
Peter

**Comment by sdanyliv** [comment]
I do not see possibility in current implementation will handle this.

**Comment by peterzt** [comment]
I have managed to do it through some sort of hack

` public static class Exts
    {
        [Sql.Expression("DataTableFTS MATCH {1}", ServerSideOnly = true, IsPredicate = true)]
        public static bool MatchFts<T>(this T x, T val) where T : IComparable<T>
        {
            throw new NotSupportedException();
        }
    }
...
                var _list = _dbData.Where(arg => arg.Col1.MatchFts("Joe*")).ToList();
...
`

This resulted in needed sql query

**Comment by sdanyliv** [comment]
Yes, it is possible,  but table aliases may have change, so it's why i do not accept this solution.

**Comment by peterzt** [comment]
I see but keep in mind that SQLite doesn't support alias in this case, i.e. you can't write
select * from TableFTS [t1] where [t1] match 'Joe*'
It must always be table name
select * from TableFTS [t1] where TableFTS  match 'Joe*'

SQLite FTS4.

**Comment by sdanyliv** [comment]
Can you check this variant?
```sql
select * from TableFTS [t1] where [t1].TableFTS match 'Joe*'
```

**Comment by peterzt** [comment]
Yes, this works fine.

**Comment by sdanyliv** [comment]
According to specification Sqlite's tables has hidden field named as table, so it's why it works.
Looking for better solution in your case.

**Comment by sdanyliv** [comment]
There is solution that works with current sources:
```c#
	public static class SqlLite
	{
		class MatchBuilder : Sql.IExtensionCallBuilder
		{
			public void Build(Sql.ISqExtensionBuilder builder)
			{
				var field = builder.GetExpression("src") as SqlField;
				if (field == null)
					throw new InvalidOperationException("Can not get table");

				var sqlTable = (SqlTable) field.Table;
				var newField = new SqlField
				{
					Name  = sqlTable.PhysicalName,
					Table = sqlTable
				};

				builder.AddParameter("table_field", newField);
			}
		}

		[Sql.Extension("{table_field} matches {match}", BuilderType = typeof(MatchBuilder), IsPredicate = true)]
		public static bool MatchFts<TEntity>(TEntity src, [ExprParameter]string match)
		{
			throw new InvalidOperationException();
		}
	}
```

**Comment by sdanyliv** [comment]
@peterzt, does proposed solution solve your problem?

**Comment by peterzt** [comment]
Sorry for delay, I have gone with my approach because yours one was giving NotSupportedException for linq2db package (1.8.3) from nuget (I guess new update will fix it).

**Comment by sdanyliv** [comment]
Check this one. And maybe we have fixed something in current sources.
https://github.com/linq2db/linq2db/blob/97684d01983071554c6fc12be37b1fa9367444c7/Tests/Linq/Linq/FunctionTests.cs#L457

**Comment by peterzt** [comment]
The exact error is:

> System.NotImplementedException occurred
  _HResult=-2147467263
  _message=The method or operation is not implemented.
  HResult=-2147467263
  IsTransient=false
  Message=The method or operation is not implemented.
  Source=linq2db
  StackTrace:
       at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 308
  InnerException: 


I guess I will wait for updated package and meanwhile will use original approach.

**Comment by sdanyliv** [comment]
Show me SQL and test this using your other program. Maybe Query is not valid.

**Comment by sdanyliv** [comment]
BTW, you can get pre-release package via MyGet

**Comment by MaceWindu** [comment]
fixed by #777

**Comment by peterzt** [comment]
I have verified this with latest linq2db v.1.9.0 - still not working with the suggested approach.

[TestLinq2dbBug_2017_09_23_12_54_07.zip](https://github.com/linq2db/linq2db/files/1326372/TestLinq2dbBug_2017_09_23_12_54_07.zip)

**Comment by MaceWindu** [comment]
Confirmed

**Comment by MaceWindu** [comment]
I've checked attached code. It fails with exception because you pass anonymous object to a function instead of mapping class instance. In this situation linq2db doesn't know which table it should search.
You should put filter before select call for your sample query to work.
If it is not something you want to achieve, could you provide more details on desired scenario?

**Comment by peterzt** [comment]
Yes, it is clear about it. I was having this query composed in the multiple different places in my code. And I think I could change it too.

**Comment by sdanyliv** [comment]
@peterzt, rewrite your function in the following way:
```cs
public static class SqlLite
{
	class MatchBuilder : Sql.IExtensionCallBuilder
	{
		public void Build(Sql.ISqExtensionBuilder builder)
		{
			var method = (MethodInfo) builder.Member;
			var arg = method.GetGenericArguments().Single();

			builder.AddParameter("table_field", new SqlTable(builder.Mapping, arg));
		}
	}

	[Sql.Extension("{table_field} match {match}", BuilderType = typeof(MatchBuilder), IsPredicate = true)]
	public static bool MatchFts<TEntity>([ExprParameter]string match)
	{
		throw new InvalidOperationException();
	}
}
```
It needs generic parameter but it should work anywhere.

**Comment by peterzt** [comment]
Thank you.

**Comment by MaceWindu** [comment]
@peterzt
FYI, full sqlite FTS support (not only match), coming to linq2db natively https://github.com/linq2db/linq2db/pull/1649

**Comment by alexey-leonovich** [comment]
How can I use SQLite match on pre-filtered records from the `Users` table. I'd like to do something like:
```
IQueryable<User> query = db.GetTable<User>().Where(x => !excludeUserIds.Contains(x.Id));
var validUserIds = Sql.Ext.SQLite()
   //(ITable<User>)query throws an exception
    .MatchTable((ITable<User>)query, matchFiler)
    .Take(100).Select(x => x.Id).ToList();
```
But for now I can only use filtering after SQLite match:
```
 var query = Sql.Ext.SQLite()
     .MatchTable(db.GetTable<User>(), searchQuery)
     .Where(x => !excludeCustomerIds.Contains(x.Id))
     .Take(limit).Select(x => x.Id).ToArray();
```
I expect the first one to be faster (FTS on smaller number of records). Am I wrong and both queries will have same performance?

**Comment by MaceWindu** [comment]
What SQL it should generate? I don't think it is possible as FTS5 filter always applied to table https://www.sqlite.org/fts5.html
